# Generated by Django 4.2.7 on 2023-12-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231210_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='final_date',
            new_name='end_date',
        ),
    ]
