# Generated by Django 4.2.7 on 2023-12-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_final_date_meeting_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='end_date',
            new_name='final_date',
        ),
    ]
